name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run linting
        run: npm run lint
        
      - name: Compile TypeScript
        run: npm run compile
        
      - name: Run tests
        run: npm run test
        continue-on-error: true
        
      - name: Test package creation
        run: |
          npm install -g @vscode/vsce
          vsce package --allow-missing-repository
